# Generated by Django 6.0.3 on 2026-04-06 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='pup_date',
            new_name='pub_date',
        ),
    ]
